### Open
- If a study reports frequencies from three handedness groups, (strong right, mixed, strong left) is it worth including both (1) (SR+SL)/M and (2) SR/(M + SL) (Right vs. non-right)? (1) is a more direct measure of Strong vs mixed handedness, and should definitely be included. (2) Is made of a mix of R/L and S/M, but has more power than (1), or the direct R/L comparison SR/SL. I have used SR/SL as the R/L comparison for between group effect sizes where possible, and SR/(M+L) for estimates with no control group. For SR/(M+SL) comparisons that we do include (because they are all that is available or because we decide that there is some advantage to using that over SR/SL), should this be coded as "R/L" or "S/M"? For now, I have coded SR/(M+L) as S/M, except in no-control-group comparisons, where I have coded it as R/L (here, it may be the easiest estimate to interpret for the frequency of "left-handedness").
- How to treat groups that mix professions? E.g., Peterson 1979's "Design, Art and Architecture" majors? Okay to collapse those with "Art" majors for meta-analysis? My instinct is to include these mushed estimates with every group in which they are relevant.
- Are studies that report Cohen's D between groups worth including? Jancke et al. 1997 reports handedness asymetry for right handed musicians vs right handed non-musicians. Fry et al., reports mean EHI scores for Architecture and music students, versus other students. (Either way, Jancke et al.'s estimate should not be pooled with Fry 1990)
- Is it worth reporting the estimates from studies with no control groups at all? These results are hard to interpret, and probably should not be pooled at all.
- For studies that have multiple subgroups in the creative group (e.g., Aggelton 1994 includes estimates for composers, singers, and instrumental musicians), should these creative groups be reported together or separately? I think there is udeful information in the separate groups, and it is okay and good to keep them separate. It may be useful to pool them together and separately, whenever there is are enough estimates for a subgroup to make pooling meaningful.

### Resolved
- What effect size should be used or preferred? Odds ratio, risk ratio, or risk difference? Odds ratio. This will treat the incidence of left and right handedness symetrically.
- What method should be used to find the confidence intervals for OR and RR? For **RR**, one popular R package (epitools) lists these options: "Calculates risk ratio by **unconditional maximum likelihood estimation (Wald)**, and **small sample adjustment** (small). Confidence intervals are calculated using **normal approximation** (Wald), and **normal approximation with small sample adjustment** (small), and **bootstrap method** (boot)." For **OR**, epitools lists these options: Calculates odds ratio by **median-unbiased estimation** (mid-p), **conditional maximum likelihood estimation** (Fisher), **unconditional maximum likelihood estimation (Wald)**, and **small sample adjustment** (small). Confidence intervals are calculated using **exact methods (mid-p and Fisher)**, **normal approximation (Wald)**, and **normal approximation with small sample adjustment** (small). Felix: use Agresti's method, implemented in the package PropCIs. This should handle small proportions in a good way.
- What should be done when a frequency is zero? (E.g., in Shettel-neuver 1983, or Preti 2007, where the control group has no strong left-handers). Add 1? Felix: Agresti's method should handle this well.
- How to report studies that have no direct control group? In a separate table with the effect size "frequency"? Yes.
- How can/should data be combined or pooled for studies that list several different group comparisons? For Shettel-neuber 1983, should we pool law and psychology faculty as the control group? For Peterson 1979, should we pool all non-Designs/Arch/Art majors? For Preti 2007, should Writers an Painters be combined? (I think we should pool control groups together whenever possible -- see OR (Final) for what this looks like).

