```{r}
label_var <- "All studies by task, measure, ES type"
```
```{r, cache = F}
pool_table_part <- init_pool_table()
```
```{r, cache = F}
## Separating partial and simple effects
sub <- es_individual

task_vars <- sub[["task"]] %>% unique()
partials_var <- "separate"

for (task_var in task_vars) {
    measure_vars <- sub %>%
      filter(task == task_var) %>%
      .[["measure"]] %>%
      unique()
    for (measure_var in measure_vars) {
      es_type_vars <- sub %>%
        filter(task == task_var & measure == measure_var) %>%
        .[["es_type"]] %>%
        unique()
      for(es_type_var in es_type_vars) {
        sub_meta <- sub %>% filter(task == task_var & measure == measure_var & es_type == es_type_var)
        
        ## Adding total n to meta table
        n_var <- sub_meta[["n"]] |> sum()
        n1_var <- sub_meta[["n1"]] |> sum()
        n2_var <- sub_meta[["n2"]] |> sum()
        
        m1 <- meta::metagen(data = sub_meta, studlab = study, TE = effect,
                            seTE = se, sm = "SMD")

        for (model_type_var in c("fixed", "random")) {
          pool_row <- metagen_makerow(m1, model_type = model_type_var,
                                       partials = partials_var,
                                      task = task_var,
                                       measure = measure_var, es_type = es_type_var,
                                       label = label_var,
                                      n_var = n_var,
                                      n1_var = n1_var,
                                      n2_var = n2_var)
          pool_table_part <- pool_table_part %>% add_row(pool_row)
        }
    }
  }
}
```
```{r, cache = T}
## Collapsing partial and simple effects
sub <- es_individual_collapse_partial

task_vars <- sub[["task"]] %>% unique()
partials_var <- "collapsed"


for (task_var in task_vars) {
    measure_vars <- sub %>%
      filter(task == task_var) %>%
      .[["measure"]] %>%
      unique()
    for (measure_var in measure_vars) {
      es_type_vars <- sub %>%
        filter(task == task_var & measure == measure_var) %>%
        .[["es_type"]] %>%
        unique()
      for(es_type_var in es_type_vars) {
        sub_meta <- sub %>% filter(task == task_var & measure == measure_var & es_type == es_type_var)
        m1 <- meta::metagen(data = sub_meta, studlab = study, TE = effect,
                            seTE = se, sm = "SMD")

        for (model_type_var in c("fixed", "random")) {
          pool_row <- metagen_makerow(m1, model_type = model_type_var,
                                       partials = partials_var, task = task_var,
                                       measure = measure_var, es_type = es_type_var,
                                       label = label_var)
          pool_table_part <- pool_table_part %>% add_row(pool_row)
        }
    }
  }
}

## Make function to remove duplicates (collapsed effects calculated
## when not needed)
undup <- function(pool_table) {
  unduped <- pool_table %>%
    filter(label == label_var) %>%
    distinct(task, measure, N, model_type, lower, .keep_all=TRUE) %>%
    arrange(label, task, measure, es_type, partials, effect)
  return(unduped)
}

pool_table_part <- pool_table_part %>% undup()
pool_table <- pool_table %>% add_row(pool_table_part)
```
```{r}
## Print summary table
disp_tbl <- pool_table %>% filter(label == label_var)
disp_tbl %>% pool_table_gt(title = label_var, groupname_col = "model_type")
```
```{r, results = "markup"}
## Print full metagen summaries to console
print_metagen_summaries(disp_tbl)
```
