This pooling is mathematically innapropriate because it (1) combines rho estimates with Cohen's D estimates, and (2) partial rhos/d's with simple rhos/d's; and (3) collapses across different task measures.

```{r}
label_var <- "All studies by task, measure"
```
```{r, cache = T}
pool_table_part <- init_pool_table()
```
```{r, cache = T}
## Separating partial and simple effects
sub <- es_individual

task_vars <- sub[["task"]] %>% unique()
partials_var <- "separate"
es_type_var <- "all"

for (task_var in task_vars) {
    measure_vars <- sub %>%
      filter(task == task_var) %>%
      .[["measure"]] %>%
      unique()
    for (measure_var in measure_vars) {
      sub_meta <- sub %>% filter(task == task_var & measure == measure_var)
      m1 <- meta::metagen(data = sub_meta, studlab = study, TE = effect,
                          seTE = se, sm = "SMD")

      for (model_type_var in c("fixed", "random")) {
        pool_row <- metagen_makerow(m1, model_type = model_type_var,
                                     partials = partials_var, task = task_var,
                                     measure = measure_var, es_type = es_type_var,
                                     label = label_var)
        pool_table_part <- pool_table_part %>% add_row(pool_row)
      }
  }
}

pool_table <- pool_table %>% add_row(pool_table_part)
```

```{r}
## Print summary table
disp_tbl <- pool_table %>% filter(label == label_var) %>% select(-label)
disp_tbl %>% pool_table_gt(title = label_var, groupname_col = "model_type")
```
```{r, results = "markup"}
## Print full metagen summaries to console
print_metagen_summaries(disp_tbl)
```
